version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "sam-ml-tutorial"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-g7uixeio4z67"
s3_prefix = "sam-ml-tutorial"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"

